spring:
  datasource:
    url: jdbc:mysql://192.168.1.70:4100/vessel_db?createDatabaseIfNotExist=true
    username: service
    password: service
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

server:
  port: 8080
